export enum ROUTES {
  LOGIN = "/login",
  HOME = "/dashboard/home",
  ORDER = "/dashboard/order",
  ORDER_ID = "/dashboard/order/",
  LABORATORY = "/dashboard/laboratory",
  LABORATORY_BASE = "/dashboard/laboratory/base",
  LABORATORY_BASE_TIPO = "/dashboard/laboratory/base/tipo",
  LABORATORY_COLORANTE = "/dashboard/laboratory/colorante",
  LABORATORY_REGISTRO = "/dashboard/laboratory/registro",
  LABORATORY_REGISTRO_SEARCH = "/dashboard/laboratory/registro/search",
  SETTINGS = "/dashboard/settings",
  SETTINGS_USERS = "/dashboard/settings/users",
  UNAUTHORIZED = "/unathorized",
  UNASIGNED = "/unasigned",
}
